"""empty message

Revision ID: f55e00b66a5a
Revises: 
Create Date: 2026-01-07 18:22:13.114851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f55e00b66a5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movieentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vote_average', sa.Float(), nullable=False),
    sa.Column('list_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movieentry')
    # ### end Alembic commands ###
